services:
  - type: web
    name: harubayan-admin
    env: python
    buildCommand: "pip install -r requirements.txt && python manage.py collectstatic --noinput && python manage.py migrate"
    startCommand: "gunicorn your_project_name.wsgi"
    envVars:
      - key: DEBUG
        value: false
      - key: SECRET_KEY
        sync: false
      - key: DATABASE_URL
        fromDatabase:
          name: harubayan-db
          property: connectionString

databases:
  - name: harubayan-db
    plan: free
