# Generated by Django 5.2.1 on 2025-05-17 15:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_access', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='adminuser',
            name='otp_created_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
